# Generated by Django 2.2.15 on 2020-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chalets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=5)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
