# Generated by Django 2.2.15 on 2020-09-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chalets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='chalets-img')),
                ('content', models.TextField(default=' ')),
            ],
        ),
    ]
