# Generated by Django 2.2.15 on 2020-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalet_name', models.CharField(max_length=150)),
                ('number_of_room', models.IntegerField(default=2)),
                ('number_of_person', models.IntegerField(default=2)),
                ('number_of_children', models.IntegerField(default=2)),
            ],
        ),
    ]
