# Generated by Django 4.1.6 on 2023-02-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_booknow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="bookNow",
        ),
        migrations.DeleteModel(
            name="contact",
        ),
        migrations.RenameField(
            model_name="chalet",
            old_name="status",
            new_name="available",
        ),
        migrations.AddField(
            model_name="chalet",
            name="No_of_rooms",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="chalet",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="chalet",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="chalet",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="chalet",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
