# Generated by Django 4.1.6 on 2023-02-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_delete_booknow_delete_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=14)),
                ("massage", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BookNow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("No_of_persons", models.IntegerField(default=2)),
                ("reservation_date", models.DateField()),
                ("No_of_days", models.IntegerField()),
                (
                    "chalet_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.chalet",
                    ),
                ),
            ],
        ),
    ]
