# Generated by Django 4.1.6 on 2023-02-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_contact_booknow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="firstname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
    ]
